// Zoom Video SDK Configuration
// Generated by setup script

module.exports = {
  "ZOOM_SDK_KEY": "I8V1ZcVKUhkkDnvvxVn8gMQTOGZxKdCaOFt2",
  "ZOOM_SDK_SECRET": "UdFimFLQh4DVu6y4eNvODe6ikoB6q8wWYB68",
  "DEBUG": true,
  "JWT_EXPIRATION": 72000
};
